In [18]:
import torch
from torch.utils.data import TensorDataset, DataLoader

# Create even smaller dummy data
data = torch.randn((10, 3, 4, 4))  # Assuming you have 10 samples, each with shape (3, 64, 64)
labels = torch.randint(0, 2, (10,))  # Binary labels (0 or 1)

# Create a TensorDataset
tensor_dataset = TensorDataset(data, labels)

#Create a Sampler to specify how you want to draw samples from the dataset


#set seed of shuffle to get the same result

# Create a DataLoader
batch_size = 5
shuffle = True
num_workers = 2
data_loader = DataLoader(tensor_dataset, batch_size=batch_size, num_workers=num_workers, shuffle=shuffle)

torch.manual_seed(0)

for e in range(2):
    for i, batch in enumerate(data_loader):
        input_data, target_labels = batch
        print(target_labels)
print('------------------')

torch.manual_seed(0)

for e in range(2):
    for i, batch in enumerate(data_loader):
        input_data, target_labels = batch
        print(target_labels)

print('------------------')

for e in range(2):
    for i, batch in enumerate(data_loader):
        input_data, target_labels = batch
        print(target_labels)


tensor([1, 0, 1, 1, 1])
tensor([1, 0, 1, 1, 0])
tensor([1, 1, 0, 1, 1])
tensor([0, 0, 1, 1, 1])
------------------
tensor([1, 0, 1, 1, 1])
tensor([1, 0, 1, 1, 0])
tensor([1, 1, 0, 1, 1])
tensor([0, 0, 1, 1, 1])
------------------
tensor([0, 1, 0, 1, 0])
tensor([1, 1, 1, 1, 1])
tensor([1, 1, 1, 1, 1])
tensor([0, 1, 0, 1, 0])
